### ISSUE TITLE
There are little inconsistencies in the design of the home page.

### ISSUE THREAD

**Issue by GuyEternal** [king0203/Winter-Project-#2]
I'd like to work on this issue.

**Comment by darshanarkhade** [comment]
I'm assigning this issue to you, and I appreciate your help .

**Comment by GuyEternal** [comment]
#4

**Comment by redtree0** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!Jhchonchol5221, @Lugdunumn, @mattdanielbrown, @vigneshpp, @Rainlove6, @oilyn0s3, @momansoury, @i0Ek3, @KUBIX90, @obarbier, @encoreshao, @qdmudong, @leolujuyi, @baifengbai, @East-E, @gituser-chinmay, @xanderdeseyn, @0xDecntralizer, @Slavaa00, @danieldomanski
